class CheckList {
  final String checkList = '''
            {
    "Status": "Ok",
    "data": {
        "Response": [
            {
                "CheckListId": 34,
                "SubProcessId": 4,
                "ProcessId": 3,
                "Description": "Mechanical Installation Status",
                "SeqNo": 1,
                "InputType": "boolean",
                "InputText": null,
                "Value": null,
                "SubProcessName": "Visual Checks",
                "ProcessName": "DRY COMMISSIONING",
                "ApprovedStatus": 0,
                "WorkedBy": 0,
                "WorkedOn": "0001-01-01T00:00:00",
                "ApprovedBy": 0,
                "ApprovedOn": "0001-01-01T00:00:00",
                "TempDT": "0001-01-01T00:00:00",
                "Remark": null,
                "ApprovalRemark": null,
                "imageByteArray": null,
                "IsMultiValue": 0,
                "SubChakQty": 6,
                "DeviceType": null,
                "Downlink": null,
                "MacAddress": null,
                "SubscribeTopicName": null,
                "ParameterName": null,
                "Comment": null,
                "Coordinate": null,
                "DataType": null,
                "Source": null,
                "DeviceId": 0,
                "conString": null,
                "UserId": 0,
                "SiteTeamEngineer": null
            },
            {
                "CheckListId": 35,
                "SubProcessId": 4,
                "ProcessId": 3,
                "Description": "OMS Controller Unit Installation",
                "SeqNo": 2,
                "InputType": "boolean",
                "InputText": null,
                "Value": null,
                "SubProcessName": "Visual Checks",
                "ProcessName": "DRY COMMISSIONING",
                "ApprovedStatus": 0,
                "WorkedBy": 0,
                "WorkedOn": "0001-01-01T00:00:00",
                "ApprovedBy": 0,
                "ApprovedOn": "0001-01-01T00:00:00",
                "TempDT": "0001-01-01T00:00:00",
                "Remark": null,
                "ApprovalRemark": null,
                "imageByteArray": null,
                "IsMultiValue": 0,
                "SubChakQty": 6,
                "DeviceType": null,
                "Downlink": null,
                "MacAddress": null,
                "SubscribeTopicName": null,
                "ParameterName": null,
                "Comment": null,
                "Coordinate": null,
                "DataType": null,
                "Source": null,
                "DeviceId": 0,
                "conString": null,
                "UserId": 0,
                "SiteTeamEngineer": null
            },
            {
                "CheckListId": 36,
                "SubProcessId": 4,
                "ProcessId": 3,
                "Description": "OMS Controller Box installed with Clamps & check connections (as per GAD)",
                "SeqNo": 3,
                "InputType": "boolean",
                "InputText": null,
                "Value": null,
                "SubProcessName": "Visual Checks",
                "ProcessName": "DRY COMMISSIONING",
                "ApprovedStatus": 0,
                "WorkedBy": 0,
                "WorkedOn": "0001-01-01T00:00:00",
                "ApprovedBy": 0,
                "ApprovedOn": "0001-01-01T00:00:00",
                "TempDT": "0001-01-01T00:00:00",
                "Remark": null,
                "ApprovalRemark": null,
                "imageByteArray": null,
                "IsMultiValue": 0,
                "SubChakQty": 6,
                "DeviceType": null,
                "Downlink": null,
                "MacAddress": null,
                "SubscribeTopicName": null,
                "ParameterName": null,
                "Comment": null,
                "Coordinate": null,
                "DataType": null,
                "Source": null,
                "DeviceId": 0,
                "conString": null,
                "UserId": 0,
                "SiteTeamEngineer": null
            },
            {
                "CheckListId": 346,
                "SubProcessId": 4,
                "ProcessId": 3,
                "Description": "Antenna installation & wiring check",
                "SeqNo": 4,
                "InputType": "boolean",
                "InputText": null,
                "Value": null,
                "SubProcessName": "Visual Checks",
                "ProcessName": "DRY COMMISSIONING",
                "ApprovedStatus": 0,
                "WorkedBy": 0,
                "WorkedOn": "0001-01-01T00:00:00",
                "ApprovedBy": 0,
                "ApprovedOn": "0001-01-01T00:00:00",
                "TempDT": "0001-01-01T00:00:00",
                "Remark": null,
                "ApprovalRemark": null,
                "imageByteArray": null,
                "IsMultiValue": 0,
                "SubChakQty": 6,
                "DeviceType": null,
                "Downlink": null,
                "MacAddress": null,
                "SubscribeTopicName": null,
                "ParameterName": null,
                "Comment": null,
                "Coordinate": null,
                "DataType": null,
                "Source": null,
                "DeviceId": 0,
                "conString": null,
                "UserId": 0,
                "SiteTeamEngineer": null
            },
            {
                "CheckListId": 347,
                "SubProcessId": 4,
                "ProcessId": 3,
                "Description": "Antenna Holding Pipe Installation",
                "SeqNo": 5,
                "InputType": "boolean",
                "InputText": null,
                "Value": null,
                "SubProcessName": "Visual Checks",
                "ProcessName": "DRY COMMISSIONING",
                "ApprovedStatus": 0,
                "WorkedBy": 0,
                "WorkedOn": "0001-01-01T00:00:00",
                "ApprovedBy": 0,
                "ApprovedOn": "0001-01-01T00:00:00",
                "TempDT": "0001-01-01T00:00:00",
                "Remark": null,
                "ApprovalRemark": null,
                "imageByteArray": null,
                "IsMultiValue": 0,
                "SubChakQty": 6,
                "DeviceType": null,
                "Downlink": null,
                "MacAddress": null,
                "SubscribeTopicName": null,
                "ParameterName": null,
                "Comment": null,
                "Coordinate": null,
                "DataType": null,
                "Source": null,
                "DeviceId": 0,
                "conString": null,
                "UserId": 0,
                "SiteTeamEngineer": null
            },
            {
                "CheckListId": 348,
                "SubProcessId": 4,
                "ProcessId": 3,
                "Description": "Solar Panel installation and wiring check",
                "SeqNo": 6,
                "InputType": "boolean",
                "InputText": null,
                "Value": null,
                "SubProcessName": "Visual Checks",
                "ProcessName": "DRY COMMISSIONING",
                "ApprovedStatus": 0,
                "WorkedBy": 0,
                "WorkedOn": "0001-01-01T00:00:00",
                "ApprovedBy": 0,
                "ApprovedOn": "0001-01-01T00:00:00",
                "TempDT": "0001-01-01T00:00:00",
                "Remark": null,
                "ApprovalRemark": null,
                "imageByteArray": null,
                "IsMultiValue": 0,
                "SubChakQty": 6,
                "DeviceType": null,
                "Downlink": null,
                "MacAddress": null,
                "SubscribeTopicName": null,
                "ParameterName": null,
                "Comment": null,
                "Coordinate": null,
                "DataType": null,
                "Source": null,
                "DeviceId": 0,
                "conString": null,
                "UserId": 0,
                "SiteTeamEngineer": null
            },
            {
                "CheckListId": 349,
                "SubProcessId": 4,
                "ProcessId": 3,
                "Description": "Position Sensor installed & wiring check",
                "SeqNo": 7,
                "InputType": "boolean",
                "InputText": null,
                "Value": null,
                "SubProcessName": "Visual Checks",
                "ProcessName": "DRY COMMISSIONING",
                "ApprovedStatus": 0,
                "WorkedBy": 0,
                "WorkedOn": "0001-01-01T00:00:00",
                "ApprovedBy": 0,
                "ApprovedOn": "0001-01-01T00:00:00",
                "TempDT": "0001-01-01T00:00:00",
                "Remark": null,
                "ApprovalRemark": null,
                "imageByteArray": null,
                "IsMultiValue": 0,
                "SubChakQty": 6,
                "DeviceType": null,
                "Downlink": null,
                "MacAddress": null,
                "SubscribeTopicName": null,
                "ParameterName": null,
                "Comment": null,
                "Coordinate": null,
                "DataType": null,
                "Source": null,
                "DeviceId": 0,
                "conString": null,
                "UserId": 0,
                "SiteTeamEngineer": null
            },
            {
                "CheckListId": 350,
                "SubProcessId": 4,
                "ProcessId": 3,
                "Description": "Hydraulic tubing Installation",
                "SeqNo": 8,
                "InputType": "boolean",
                "InputText": null,
                "Value": null,
                "SubProcessName": "Visual Checks",
                "ProcessName": "DRY COMMISSIONING",
                "ApprovedStatus": 0,
                "WorkedBy": 0,
                "WorkedOn": "0001-01-01T00:00:00",
                "ApprovedBy": 0,
                "ApprovedOn": "0001-01-01T00:00:00",
                "TempDT": "0001-01-01T00:00:00",
                "Remark": null,
                "ApprovalRemark": null,
                "imageByteArray": null,
                "IsMultiValue": 0,
                "SubChakQty": 6,
                "DeviceType": null,
                "Downlink": null,
                "MacAddress": null,
                "SubscribeTopicName": null,
                "ParameterName": null,
                "Comment": null,
                "Coordinate": null,
                "DataType": null,
                "Source": null,
                "DeviceId": 0,
                "conString": null,
                "UserId": 0,
                "SiteTeamEngineer": null
            },
            {
                "CheckListId": 351,
                "SubProcessId": 4,
                "ProcessId": 3,
                "Description": "Cable, Cable Tray & tube dressing",
                "SeqNo": 9,
                "InputType": "boolean",
                "InputText": null,
                "Value": null,
                "SubProcessName": "Visual Checks",
                "ProcessName": "DRY COMMISSIONING",
                "ApprovedStatus": 0,
                "WorkedBy": 0,
                "WorkedOn": "0001-01-01T00:00:00",
                "ApprovedBy": 0,
                "ApprovedOn": "0001-01-01T00:00:00",
                "TempDT": "0001-01-01T00:00:00",
                "Remark": null,
                "ApprovalRemark": null,
                "imageByteArray": null,
                "IsMultiValue": 0,
                "SubChakQty": 6,
                "DeviceType": null,
                "Downlink": null,
                "MacAddress": null,
                "SubscribeTopicName": null,
                "ParameterName": null,
                "Comment": null,
                "Coordinate": null,
                "DataType": null,
                "Source": null,
                "DeviceId": 0,
                "conString": null,
                "UserId": 0,
                "SiteTeamEngineer": null
            },
            {
                "CheckListId": 352,
                "SubProcessId": 4,
                "ProcessId": 3,
                "Description": "Door Switch installation & wiring check",
                "SeqNo": 10,
                "InputType": "boolean",
                "InputText": null,
                "Value": null,
                "SubProcessName": "Visual Checks",
                "ProcessName": "DRY COMMISSIONING",
                "ApprovedStatus": 0,
                "WorkedBy": 0,
                "WorkedOn": "0001-01-01T00:00:00",
                "ApprovedBy": 0,
                "ApprovedOn": "0001-01-01T00:00:00",
                "TempDT": "0001-01-01T00:00:00",
                "Remark": null,
                "ApprovalRemark": null,
                "imageByteArray": null,
                "IsMultiValue": 0,
                "SubChakQty": 6,
                "DeviceType": null,
                "Downlink": null,
                "MacAddress": null,
                "SubscribeTopicName": null,
                "ParameterName": null,
                "Comment": null,
                "Coordinate": null,
                "DataType": null,
                "Source": null,
                "DeviceId": 0,
                "conString": null,
                "UserId": 0,
                "SiteTeamEngineer": null
            },
            {
                "CheckListId": 356,
                "SubProcessId": 4,
                "ProcessId": 3,
                "Description": "Upload PDF",
                "SeqNo": 11,
                "InputType": "pdf",
                "InputText": null,
                "Value": null,
                "SubProcessName": "Visual Checks",
                "ProcessName": "DRY COMMISSIONING",
                "ApprovedStatus": 0,
                "WorkedBy": 0,
                "WorkedOn": "0001-01-01T00:00:00",
                "ApprovedBy": 0,
                "ApprovedOn": "0001-01-01T00:00:00",
                "TempDT": "0001-01-01T00:00:00",
                "Remark": null,
                "ApprovalRemark": null,
                "imageByteArray": null,
                "IsMultiValue": 0,
                "SubChakQty": 6,
                "DeviceType": null,
                "Downlink": null,
                "MacAddress": null,
                "SubscribeTopicName": null,
                "ParameterName": null,
                "Comment": null,
                "Coordinate": null,
                "DataType": null,
                "Source": null,
                "DeviceId": 0,
                "conString": null,
                "UserId": 0,
                "SiteTeamEngineer": null
            },
            {
                "CheckListId": 48,
                "SubProcessId": 4,
                "ProcessId": 3,
                "Description": "Overall Interior of Enclosure Filter / PFCMD section",
                "SeqNo": 12,
                "InputType": "image",
                "InputText": null,
                "Value": null,
                "SubProcessName": "Visual Checks",
                "ProcessName": "DRY COMMISSIONING",
                "ApprovedStatus": 0,
                "WorkedBy": 0,
                "WorkedOn": "0001-01-01T00:00:00",
                "ApprovedBy": 0,
                "ApprovedOn": "0001-01-01T00:00:00",
                "TempDT": "0001-01-01T00:00:00",
                "Remark": null,
                "ApprovalRemark": null,
                "imageByteArray": null,
                "IsMultiValue": 0,
                "SubChakQty": 6,
                "DeviceType": null,
                "Downlink": null,
                "MacAddress": null,
                "SubscribeTopicName": null,
                "ParameterName": null,
                "Comment": null,
                "Coordinate": null,
                "DataType": null,
                "Source": null,
                "DeviceId": 0,
                "conString": null,
                "UserId": 0,
                "SiteTeamEngineer": null
            },
            {
                "CheckListId": 49,
                "SubProcessId": 4,
                "ProcessId": 3,
                "Description": "Overall Interior of Enclosure PFCMD / ROMS section",
                "SeqNo": 13,
                "InputType": "image",
                "InputText": null,
                "Value": null,
                "SubProcessName": "Visual Checks",
                "ProcessName": "DRY COMMISSIONING",
                "ApprovedStatus": 0,
                "WorkedBy": 0,
                "WorkedOn": "0001-01-01T00:00:00",
                "ApprovedBy": 0,
                "ApprovedOn": "0001-01-01T00:00:00",
                "TempDT": "0001-01-01T00:00:00",
                "Remark": null,
                "ApprovalRemark": null,
                "imageByteArray": null,
                "IsMultiValue": 0,
                "SubChakQty": 6,
                "DeviceType": null,
                "Downlink": null,
                "MacAddress": null,
                "SubscribeTopicName": null,
                "ParameterName": null,
                "Comment": null,
                "Coordinate": null,
                "DataType": null,
                "Source": null,
                "DeviceId": 0,
                "conString": null,
                "UserId": 0,
                "SiteTeamEngineer": null
            },
            {
                "CheckListId": 50,
                "SubProcessId": 4,
                "ProcessId": 3,
                "Description": "Exterior of the Enclosure with Solar Panel and Antenna",
                "SeqNo": 14,
                "InputType": "image",
                "InputText": null,
                "Value": null,
                "SubProcessName": "Visual Checks",
                "ProcessName": "DRY COMMISSIONING",
                "ApprovedStatus": 0,
                "WorkedBy": 0,
                "WorkedOn": "0001-01-01T00:00:00",
                "ApprovedBy": 0,
                "ApprovedOn": "0001-01-01T00:00:00",
                "TempDT": "0001-01-01T00:00:00",
                "Remark": null,
                "ApprovalRemark": null,
                "imageByteArray": null,
                "IsMultiValue": 0,
                "SubChakQty": 6,
                "DeviceType": null,
                "Downlink": null,
                "MacAddress": null,
                "SubscribeTopicName": null,
                "ParameterName": null,
                "Comment": null,
                "Coordinate": null,
                "DataType": null,
                "Source": null,
                "DeviceId": 0,
                "conString": null,
                "UserId": 0,
                "SiteTeamEngineer": null
            },
            {
                "CheckListId": 51,
                "SubProcessId": 4,
                "ProcessId": 3,
                "Description": "SCADA configuration",
                "SeqNo": 15,
                "InputType": "image",
                "InputText": null,
                "Value": null,
                "SubProcessName": "Visual Checks",
                "ProcessName": "DRY COMMISSIONING",
                "ApprovedStatus": 0,
                "WorkedBy": 0,
                "WorkedOn": "0001-01-01T00:00:00",
                "ApprovedBy": 0,
                "ApprovedOn": "0001-01-01T00:00:00",
                "TempDT": "0001-01-01T00:00:00",
                "Remark": null,
                "ApprovalRemark": null,
                "imageByteArray": null,
                "IsMultiValue": 0,
                "SubChakQty": 6,
                "DeviceType": null,
                "Downlink": null,
                "MacAddress": null,
                "SubscribeTopicName": null,
                "ParameterName": null,
                "Comment": null,
                "Coordinate": null,
                "DataType": null,
                "Source": null,
                "DeviceId": 0,
                "conString": null,
                "UserId": 0,
                "SiteTeamEngineer": null
            },
            {
                "CheckListId": 52,
                "SubProcessId": 4,
                "ProcessId": 3,
                "Description": "Image 5",
                "SeqNo": 16,
                "InputType": "image",
                "InputText": null,
                "Value": null,
                "SubProcessName": "Visual Checks",
                "ProcessName": "DRY COMMISSIONING",
                "ApprovedStatus": 0,
                "WorkedBy": 0,
                "WorkedOn": "0001-01-01T00:00:00",
                "ApprovedBy": 0,
                "ApprovedOn": "0001-01-01T00:00:00",
                "TempDT": "0001-01-01T00:00:00",
                "Remark": null,
                "ApprovalRemark": null,
                "imageByteArray": null,
                "IsMultiValue": 0,
                "SubChakQty": 6,
                "DeviceType": null,
                "Downlink": null,
                "MacAddress": null,
                "SubscribeTopicName": null,
                "ParameterName": null,
                "Comment": null,
                "Coordinate": null,
                "DataType": null,
                "Source": null,
                "DeviceId": 0,
                "conString": null,
                "UserId": 0,
                "SiteTeamEngineer": null
            }
        ],
        "Status": "Ok",
        "Message": null
    }
}
       ''';
}
